service: newton-fractal
runtime: nodejs16

handlers:
  - url: /
    secure: always
    static_files: dist/newton-fractal/index.html
    upload: dist/newton-fractal/index.html

  #  Routing rules for resources, css, js, images etc. Any file with format filename.ext
  - url: /(.*\.(.+))$
    secure: always
    static_files: dist/newton-fractal/\1
    upload: dist/newton-fractal/(.*\.(.+))$

  #  Routing rule for Angular Routing
  - url: /(.*)
    secure: always
    static_files: dist/newton-fractal/index.html
    upload: dist/newton-fractal/index.html